Repository vivo-project/Vitro, pull requests merged in 2022-04, with the labels that each got.

#241 Online translation
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/i18n/I18nBundle.java
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/i18n/freemarker/I18nStringTemplateModel.java
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/utils/developer/Key.java
  home/src/main/resources/config/example.developer.properties
  webapp/src/main/webapp/js/account/accountProxyItemsPanel.js
  webapp/src/main/webapp/js/developer/FileSaver.js
  webapp/src/main/webapp/js/developer/developerPanel.js
  webapp/src/main/webapp/js/developer/translations.js
  webapp/src/main/webapp/templates/freemarker/page/partials/developer.ftl
  webapp/src/main/webapp/templates/freemarker/page/partials/developerPanel.ftl
Labels: large PR

#250 Creating Locale with specified Language script
  README.md
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/i18n/selection/LocaleSelectionController.java
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/i18n/selection/LocaleSelectionDataGetter.java
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/i18n/selection/LocaleSelectionSetup.java
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/utils/LocaleUtility.java
Labels: small PR

#252 [VIVO-1841] - Add POST body support to update api
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/api/SparqlUpdateApiController.java
Labels: middle PR

#240 Add password authentification on external smtp servers
  api/src/main/java/edu/cornell/mannlib/vitro/webapp/email/FreemarkerEmailFactory.java
  home/src/main/resources/config/example.runtime.properties
Labels: small PR
